from enum import StrEnum


class ProcurementAnalysisStatus(StrEnum):
    PENDING_ANALYSIS = "PENDING_ANALYSIS"
    ANALYSIS_IN_PROGRESS = "ANALYSIS_IN_PROGRESS"
    ANALYSIS_SUCCESSFUL = "ANALYSIS_SUCCESSFUL"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    TIMEOUT = "TIMEOUT"
