blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mthunsche/public-detective/discussions/new?category=q-a
    about: Ask and answer questions
  - name: Request a feature
    url: https://github.com/mthunsche/public-detective/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/mthunsche/public-detective/security/policy
    about: Learn how to notify us of a security issue
